"""
Company registry for the ATS poller.

Each entry maps a company to the ATS platform it posts jobs on, plus
whatever identifier that platform's API needs to look it up. Verified by
hitting the platform's public JSON API directly (see PR/commit history) --
don't add an entry here without confirming the API actually returns data
for that slug/tenant.

IMPORTANT: after adding one or more companies here, run
`python3 ats_poller/backfill_seen.py` and commit the resulting
seen_ats.json change IN THE SAME COMMIT, before pushing. Without it, the
next real poll run treats every one of the new company's current open
postings as brand new and alerts on its entire backlog at once (this
happened on 2026-08-25 with a 185-company batch: 400+ unwanted Telegram
messages went out from two overlapping production runs before seen_ats.json
caught up -- see backfill_seen.py's docstring for the full story).
"""

GREENHOUSE_COMPANIES = [
    # display_name, board_slug
    ("Coinbase", "coinbase"),
    ("Waymo", "waymo"),
    ("Block", "block"),
    ("Anthropic", "anthropic"),
    ("Cloudflare", "cloudflare"),
    ("Stripe", "stripe"),
    ("Dropbox", "dropbox"),
    ("Duolingo", "duolingo"),
    ("Figma", "figma"),
    ("Databricks", "databricks"),
    ("Robinhood", "robinhood"),
    ("Ripple", "ripple"),
    ("Airtable", "airtable"),
    ("Airbnb", "airbnb"),
    ("Pinterest", "pinterest"),
    ("Reddit", "reddit"),
    ("Discord", "discord"),
    ("Twitch", "twitch"),
    ("Roblox", "roblox"),
    ("Epic Games", "epicgames"),
    ("Riot Games", "riotgames"),
    ("Asana", "asana"),
    ("Datadog", "datadog"),
    ("MongoDB", "mongodb"),
    ("Elastic", "elastic"),
    ("GitLab", "gitlab"),
    ("JetBrains", "jetbrains"),
    ("Vercel", "vercel"),
    ("Netlify", "netlify"),
    ("Twilio", "twilio"),
    ("Okta", "okta"),
    ("Zscaler", "zscaler"),
    ("Scale AI", "scaleai"),
    ("xAI", "xai"),
    ("DeepMind", "deepmind"),
    ("Inflection AI", "inflectionai"),
    ("Stability AI", "stabilityai"),
    ("Together AI", "togetherai"),
    ("Graphcore", "graphcore"),
    ("Tenstorrent", "tenstorrent"),
    ("Ubiquiti", "ubiquiti"),
    ("Rubrik", "rubrik"),
    ("Pure Storage", "purestorage"),
    ("Canonical", "canonical"),
    ("Cockroach Labs", "cockroachlabs"),
    ("PlanetScale", "planetscale"),
    ("Fivetran", "fivetran"),
    ("LaunchDarkly", "launchdarkly"),
    ("PagerDuty", "pagerduty"),
    ("New Relic", "newrelic"),
    ("Grafana Labs", "grafanalabs"),
    ("Honeycomb", "honeycomb"),
    ("Samsara", "samsara"),
    ("Motional", "motional"),
    ("Nuro", "nuro"),
    ("SpaceX", "spacex"),
    ("Rocket Lab", "rocketlab"),
    ("Planet Labs", "planetlabs"),
    ("Astranis", "astranis"),
    ("Lucid Motors", "lucidmotors"),
    ("Figure AI", "figureai"),
    ("Agility Robotics", "agilityrobotics"),
    ("Chime", "chime"),
    ("Affirm", "affirm"),
    ("Brex", "brex"),
    ("Mercury", "mercury"),
    ("Betterment", "betterment"),
    ("SoFi", "sofi"),
    ("Marqeta", "marqeta"),
    ("Adyen", "adyen"),
    ("Wise", "wise"),
    ("Jane Street", "janestreet"),
    ("Jump Trading", "jumptrading"),
    ("Akuna Capital", "akunacapital"),
    ("Optiver", "optiver"),
    ("Point72", "point72"),
    ("Instacart", "instacart"),
    ("Lyft", "lyft"),
    ("Squarespace", "squarespace"),
    ("Klaviyo", "klaviyo"),
    ("Intercom", "intercom"),
    ("Gusto", "gusto"),
    ("Remote", "remote"),
    ("Checkr", "checkr"),
    ("Carta", "carta"),
    ("LG Electronics", "lgelectronics"),
    ("Western Union", "westernunion"),
    ("McAfee", "mcafee"),
    ("Fastly", "fastly"),
    ("Peloton", "peloton"),
    ("Oura", "oura"),
    ("Coursera", "coursera"),
    ("Udemy", "udemy"),
    ("Udacity", "udacity"),
    ("Khan Academy", "khanacademy"),
    ("2U", "2u"),
    ("IXL Learning", "ixllearning"),
    ("ZipRecruiter", "ziprecruiter"),
    ("LinkedIn", "linkedin"),
    ("Upwork", "upwork"),
    ("Turing", "turing"),
    ("Instawork", "instawork"),
    ("Flex", "flex"),
    ("Venture Global", "ventureglobal"),
    ("Verkada", "verkada"),
    ("Tenable", "tenableinc"),
    # Added from SimplifyJobs listings.json migration on 2026-08-24, verified via each platform's own API/page metadata
    ("10a Labs", "10alabs"),
    ("Alayacare", "alayacare"),
    ("AlixPartners", "alixpartners"),
    ("Altamira Technologies", "altamiratechnologies"),
    ("Appian", "appian"),
    ("Apptronik", "apptronik"),
    ("Aquatic Capital Management", "aquaticcapitalmanagement"),
    ("Argmax", "argmax"),
    ("Artisan Partners", "artisanpartners"),
    ("ASM International", "asm"),
    ("Astera Labs", "asteralabs"),
    ("Atoms", "atoms"),
    ("Audax Group", "audaxgroup"),
    ("Axiomatic AI", "axiomaticai"),
    ("Axon", "axon"),
    ("BlackEdge Capital", "blackedgecapital"),
    ("Bluestaq", "bluestaq"),
    ("Bot Auto", "botauto"),
    ("Clerkie", "clerkie"),
    ("Cresta", "cresta"),
    ("Detroit Lions", "detroitlions"),
    ("Dmg Media", "dmgmedia"),
    ("Docugami", "docugami"),
    ("DV Trading", "dvtrading"),
    ("Etched.ai", "etchedai"),
    ("Eudia", "eudia"),
    ("Eulerity", "eulerity"),
    ("Everstream Analytics", "everstreamanalytics"),
    ("Evolver", "evolver"),
    ("Faire", "faire"),
    ("Figure", "figure"),
    ("Flow Traders", "flowtraders"),
    ("Formlabs", "formlabs"),
    ("Four Hands", "fourhands"),
    ("General Matter", "generalmatter"),
    ("Gensyn", "gensyn"),
    ("Ginkgo Bioworks", "ginkgobioworks"),
    ("Haize Labs", "haizelabs"),
    ("Helsing", "helsing"),
    ("Hone Health", "honehealth"),
    ("Incident IQ", "incidentiq"),
    ("Instead", "instead"),
    ("Later", "later"),
    ("Lila Sciences", "lilasciences"),
    ("Mach Industries", "machindustries"),
    ("Medical Informatics Engineering", "medicalinformaticsengineering"),
    ("Neuralink", "neuralink"),
    ("NewsBreak", "newsbreak"),
    ("Nextiva", "nextiva"),
    ("Orennia", "orennia"),
    ("PDT Partners", "pdtpartners"),
    ("Postman", "postman"),
    ("PsiQuantum", "psiquantum"),
    ("Quantbot Technologies", "quantbot-technologies"),
    ("Samsung Research America", "samsungresearchamerica"),
    ("Seven Research", "sevenresearch"),
    ("Sezzle", "sezzle"),
    ("SHEIN", "shein"),
    ("Solid Power", "solidpower"),
    ("Squarepoint Capital", "squarepointcapital"),
    ("Super", "super"),
    ("Syska Hennessy Group", "syskahennessy"),
    ("The Nuclear Company", "thenuclearcompany"),
    ("TIFIN", "tifin"),
    ("Tower Research Capital", "towerresearchcapital"),
    ("TransMarket Group", "transmarketgroup"),
    ("Chicago Trading Company", "chicagotrading"),
    ("TribalScale", "tribalscale"),
    ("Truveta", "truveta"),
    ("Varda Space", "vardaspace"),
    ("Weave", "weave"),
    ("Workato", "workato"),
    ("Xantium", "xantium"),
    ("XPENG Motors", "xpengmotors"),
]

LEVER_COMPANIES = [
    # display_name, company_slug
    ("Palantir", "palantir"),
    ("Neon", "neon"),
    ("Zoox", "zoox"),
    ("Shield AI", "shieldai"),
    ("Wealthfront", "wealthfront"),
    ("AngelList", "angellist"),
    ("Extreme Networks", "extremenetworks"),
    # Added from SimplifyJobs listings.json migration on 2026-08-24, verified via each platform's own API/page metadata
    ("Acceldata", "acceldata"),
    ("Alertus Technologies", "alertus"),
    ("Belvedere Trading", "belvederetrading"),
    ("Binance", "binance"),
    ("CALSTART", "calstart"),
    ("Catalist", "catalist"),
    ("Diversified Automation", "diversified-automation"),
    ("E-Space", "espace"),
    ("Hermeus", "hermeus"),
    ("Intropic", "intropic"),
    ("Magnet Forensics", "magnetforensics"),
    ("Multiply Labs", "multiplylabs"),
    ("ShyftLabs", "shyftlabs"),
    ("Veeva", "veeva"),
    ("Xsolla", "xsolla"),
]

ASHBY_COMPANIES = [
    # display_name, job_board_slug
    ("OpenAI", "openai"),
    ("Perplexity", "perplexity"),
    ("Cohere", "cohere"),
    ("Cerebras", "cerebras"),
    ("Harvey", "harvey"),
    ("Replit", "replit"),
    ("Runway", "runway"),
    ("ElevenLabs", "elevenlabs"),
    ("Supabase", "supabase"),
    ("Notion", "notion"),
    ("Ramp", "ramp"),
    ("Linear", "linear"),
    ("Vercel", "vercel"),
    ("Snowflake", "snowflake"),
    ("Pika", "pika"),
    ("Baseten", "baseten"),
    ("Deepgram", "deepgram"),
    ("Sierra", "sierra"),
    ("Writer", "writer"),
    ("Pinecone", "pinecone"),
    ("Weaviate", "weaviate"),
    ("Temporal", "temporal"),
    ("Warp", "warp"),
    ("Raycast", "raycast"),
    ("Browserbase", "browserbase"),
    ("Render", "render"),
    ("Railway", "railway"),
    ("Clerk", "clerk"),
    ("WorkOS", "workos"),
    ("Resend", "resend"),
    ("Wiz", "wiz"),
    ("Snyk", "snyk"),
    ("Cursor", "cursor"),
    ("Magic Patterns", "magicpatterns"),
    ("LangChain", "langchain"),
    ("Crusoe", "crusoe"),
    ("Lambda", "lambda"),
    ("Midjourney", "midjourney"),
    ("Physical Intelligence", "physicalintelligence"),
    ("Deel", "deel"),
    ("Convex", "convex-dev"),
    ("AfterQuery", "afterquery"),
    ("Agave", "agave"),
    ("Airbyte", "airbyte"),
    ("Anyscale", "anyscale"),
    ("Ashby", "ashby"),
    ("Auctor", "auctor"),
    ("Bland AI", "bland"),
    ("Circleback", "circleback"),
    ("Letta", "letta"),
    ("Modal", "modal"),
    ("Retell AI", "retell-ai"),
    ("Speak", "speak"),
    ("Uncountable", "uncountable"),
    ("Vapi", "vapi"),
    ("Giga", "gigaml"),
    ("Sentry", "sentry"),
    ("1Password", "1password"),
    ("Mistral AI", "mistral.ai"),
    ("Docker", "docker"),
    # Added from SimplifyJobs listings.json migration on 2026-08-24, verified via each platform's own API/page metadata
    ("1X", "1x"),
    ("Abridge", "abridge"),
    ("Abundant", "abundant"),
    ("AeroVect", "aerovect"),
    ("Ambrook", "ambrook"),
    ("Ampersand", "ampersand"),
    ("Arlo", "arlo"),
    ("Astera", "astera"),
    ("Base Power", "base-power"),
    ("Beacon Software", "beaconsoftware"),
    ("Bild AI", "bild-ai"),
    ("Bree", "bree"),
    ("Centerfield", "centerfield"),
    ("Composio", "composio"),
    ("Constellation Space", "constellationspace"),
    ("CTGT", "ctgt"),
    ("CuspAI", "cuspai"),
    ("Dedalus Labs", "dedalus-labs"),
    ("Denari", "denari"),
    ("Dexmate", "dexmate"),
    ("Dryft", "dryft"),
    ("Ellipsis Labs", "ellipsislabs"),
    ("Epia Neuro", "epianeuro"),
    ("Eragon", "eragon"),
    ("Etched", "etched"),
    ("Firetiger", "firetiger"),
    ("Forus", "forus"),
    ("Frontier Health", "frontier-health"),
    ("Fundwell", "fundwell"),
    ("H3X Technologies", "h3x-technologies"),
    ("HCompany", "hcompany"),
    ("Heliux", "heliux"),
    ("Heron Power", "heron-power"),
    ("Hiverge", "hiverge"),
    ("Human Computer Lab", "human-computer-lab"),
    ("Inherent", "inherent"),
    ("k-ID", "k-id"),
    ("Kirin", "kirin"),
    ("Kognitos", "kognitos"),
    ("Leland", "leland"),
    ("Maxima", "maxima"),
    ("Melius", "melius"),
    ("Mercor", "mercor"),
    ("Meshy", "meshy"),
    ("Mosaic", "mosaic"),
    ("NeoCognition", "neocognition"),
    ("Niural", "niural"),
    ("NTT DATA AIVista", "ntt-data-aivista"),
    ("OpusClip", "opusclip"),
    ("Phonely", "phonely"),
    ("Phonic", "phonic"),
    ("Pivot Robotics", "pivotrobotics"),
    ("Prior Labs", "prior-labs"),
    ("Pylon", "pylon"),
    ("Rainmaker", "rainmaker"),
    ("Rho", "rho"),
    ("Serval", "serval"),
    ("Skydio", "skydio"),
    ("Sweatpals", "sweatpals"),
    ("Tacit", "tacit"),
    ("Terranova", "terranova"),
    ("Tessera Labs", "tessera-labs"),
    ("Tilde Research", "tilderesearch"),
    ("Unify", "unify"),
    ("Valstad", "valstad"),
    ("Vendelux", "vendelux"),
    ("Vital Lyfe", "vital-lyfe"),
    ("WindBorne Systems", "windborne-systems"),
    ("Zello", "zello"),
    ("Zuru", "zuru"),
]

WORKDAY_COMPANIES = [
    # display_name, tenant, wd_host (e.g. "wd5"), site
    ("Adobe", "adobe", "wd5", "external_experienced"),
    ("Nvidia", "nvidia", "wd5", "NVIDIAExternalCareerSite"),
    ("Intel", "intel", "wd1", "External"),
    ("Analog Devices", "analogdevices", "wd1", "External"),
    ("Micron", "micron", "wd1", "External"),
    ("Cadence", "cadence", "wd1", "External_Careers"),
    ("Chewy", "chewy", "wd5", "External"),
    ("Vanguard", "vanguard", "wd5", "vanguard_External"),
    ("State Street", "statestreet", "wd1", "Global"),
    ("Boeing", "boeing", "wd1", "External_Careers"),
    ("Leidos", "leidos", "wd5", "External"),
    ("CACI", "caci", "wd1", "External"),
    ("Qualys", "qualys", "wd5", "Careers"),
    ("Trend Micro", "trendmicro", "wd3", "External"),
    ("Ciena", "ciena", "wd5", "Careers"),
    ("Pluralsight", "pluralsight", "wd1", "Careers"),
    ("3M", "3m", "wd1", "Search"),
    ("AES", "aes", "wd1", "AES_US"),
    ("Amgen", "amgen", "wd1", "Careers"),
    ("Applied Materials", "amat", "wd1", "External"),
    ("Arrow Electronics", "arrow", "wd1", "AC"),
    ("Bank of America", "ghr", "wd1", "Lateral-US"),
    ("Becton Dickinson", "bdx", "wd1", "EXTERNAL_CAREER_SITE_USA"),
    ("Biogen", "biibhr", "wd3", "external"),
    ("Bristol-Myers Squibb", "bristolmyerssquibb", "wd5", "BMS"),
    ("CDW", "cdw", "wd5", "Careers"),
    ("Chevron", "chevron", "wd5", "jobs"),
    ("Cigna", "cigna", "wd5", "cignacareers"),
    ("CrowdStrike", "crowdstrike", "wd5", "crowdstrikecareers"),
    ("Conagra Brands", "conagrabrands", "wd1", "Careers_US"),
    ("ConocoPhillips", "conocophillips", "wd1", "eQuest"),
    ("Duke Energy", "dukeenergy", "wd1", "Search"),
    ("Expedia", "expedia", "wd108", "search"),
    ("Fidelity", "fmr", "wd1", "FidelityCareers"),
    ("Fiserv", "fiserv", "wd5", "EXT"),
    ("General Motors", "generalmotors", "wd5", "Careers_GM"),
    ("Gilead Sciences", "gilead", "wd1", "gileadcareers"),
    ("KLA", "kla", "wd1", "Search"),
    ("Mastercard", "mastercard", "wd1", "CorporateCareers"),
    ("Mastercard Campus", "mastercard", "wd1", "Campus"),
    ("Merck", "msd", "wd5", "SearchJobs"),
    ("Motorola Solutions", "motorolasolutions", "wd5", "Careers"),
    ("Pfizer", "pfizer", "wd1", "PfizerCareers"),
    ("Rockwell Automation", "rockwellautomation", "wd1", "External_Rockwell_Automation"),
    ("S&P Global", "spgi", "wd5", "SPGI_Careers"),
    ("Prudential Financial", "pru", "wd5", "Careers"),
    ("RTX", "globalhr", "wd5", "REC_RTX_Ext_Gateway"),
    ("Travelers", "travelers", "wd5", "External"),
    ("Truist Financial", "truist", "wd1", "Careers"),
    ("NXP Semiconductors", "nxp", "wd3", "Careers"),
    ("Broadcom", "broadcom", "wd1", "External_Career"),
    ("Booz Allen Hamilton", "bah", "wd1", "BAH_Jobs"),
    ("Samsung", "sec", "wd3", "Samsung_Careers"),
    ("Autodesk", "autodesk", "wd1", "Ext"),
    ("F5", "ffive", "wd5", "f5jobs"),
    ("HPE", "hpe", "wd5", "Jobsathpe"),
    ("Marvell", "marvell", "wd1", "MarvellCareers"),
    ("Xylem", "xylem", "wd5", "xylem-careers"),
    ("Otis Worldwide", "otis", "wd504", "REC_Ext_Gateway"),
    ("GE Vernova", "gevernova", "wd5", "Vernova_ExternalSite"),
    ("Stryker", "stryker", "wd1", "StrykerCareers"),
    ("IQVIA", "iqvia", "wd1", "IQVIA"),
    ("Thermo Fisher Scientific", "thermofisher", "wd5", "ThermoFisherCareers"),
    ("Danaher", "danaher", "wd1", "DanaherJobs"),
    ("Illinois Tool Works", "itw", "wd5", "External"),
    ("Red Hat", "redhat", "wd5", "jobs"),
    ("Boston Dynamics", "bostondynamics", "wd1", "Boston_Dynamics"),
    ("Unity", "unitytech", "wd1", "Unity"),
]

# Not added, verified wrong or unresolvable when the user pasted a claimed
# Workday company list on 2026-08-19 (see git history for the fork's full
# verification report):
# - Wrong platform entirely (no adapter for these here): AMD (iCIMS),
#   Boston Scientific (Eightfold), Emerson Electric (Oracle Fusion), Ford
#   (Oracle Fusion), Honeywell (Oracle Fusion), Lam Research (Eightfold),
#   Texas Instruments (Oracle Fusion), United Airlines (Taleo -- the
#   uaa.wd12 Workday tenant found is only their flight-school subsidiary).
# - Not actually this company's board: Aflac (hit was Children's Healthcare
#   of Atlanta's "Aflac Cancer Center"), Cintas (hit was Northrop Grumman's
#   vendor board mentioning Cintas).
# - Stale: Discover Financial (being retired into Capital One's board
#   post-acquisition).
# - No working tenant/site found within a reasonable search budget:
#   Accenture, Abbott Laboratories (already covered separately via
#   custom_sites/adapters/abbott_careers.py on jobs.abbott, a different
#   site), Amphenol, Aramark, Archer Daniels Midland, Baker Hughes, Baxter
#   International, BlackRock, Blackstone, Bunge, C.H. Robinson Worldwide,
#   Capital One, CBRE, Citi, Comcast, Ecolab, Eli Lilly, Intuit, Jabil,
#   Johnson & Johnson, Northrop Grumman, Palo Alto Networks, Procter &
#   Gamble, Stryker, T-Mobile US, Thermo Fisher Scientific, UnitedHealth,
#   Verizon, Wells Fargo -- revisit if worth the WebSearch time later.
#
# Checked against candidates.txt on 2026-08-21 (see git history for the
# fork's full verification report):
# - Wrong platform / own careers portal: Qualcomm, TSMC, Seagate, Synopsys
#   (Avature), ON Semiconductor, Skyworks Solutions, STMicroelectronics
#   (Eightfold), Infineon Technologies, Corning, Fortinet, Check Point
#   Software, Akamai, Lockheed Martin, General Dynamics, L3Harris, SAIC
#   (Taleo), SAP, Oracle, Goldman Sachs, JPMorgan Chase, Charles Schwab
#   (myworkdayjobs hit was unrelated "Les Schwab" tire company), Garmin,
#   American Express.
# - Acquired/consolidated, not standalone: Splunk (now part of Cisco's
#   board).
# - Already tracked elsewhere: edX (via 2U, Greenhouse).
# - Real Workday tenant found but no working site guessed yet -- revisit:
#   Dell Technologies (tenant resolves, 0 postings on guessed sites),
#   Chegg (tenant osv-chegg.wd5 real, neither "Chegg" nor "USA" site
#   guess returned data).

SMARTRECRUITERS_COMPANIES = [
    # display_name, company_identifier (as used in the API path)
    ("AbbVie", "abbvie"),
    ("Avery Dennison", "averydennison"),
    ("Builders FirstSource", "buildersfirstsource"),
    ("Celanese", "celanese"),
    ("Cencora", "cencora"),
    ("Freeport-McMoRan", "freeport-mcmoran"),
    ("Glean", "glean"),
    ("Henry Schein", "henryschein"),
    ("Kenvue", "kenvue"),
    ("Kimberly-Clark", "kimberlyclark"),
    ("Land O'Lakes", "landolakes"),
    ("Live Nation Entertainment", "livenationentertainment"),
    ("MGM Resorts International", "mgmresortsinternational"),
    ("Markel", "markel"),
    ("News Corp.", "newscorp"),
    ("Northwestern Mutual", "northwesternmutual"),
    ("ServiceNow", "servicenow"),
    ("Sonic Automotive", "sonicautomotive"),
    ("Western Digital", "westerndigital"),
    # Added from SimplifyJobs listings.json migration on 2026-08-24, verified via each platform's own API/page metadata
    ("Canva", "canva"),
    ("Clinical Ink", "clinicalink"),
    ("Codeage", "codeage"),
    ("Encephalo Investments", "encephaloinvestments"),
    ("Eurofins", "eurofins"),
    ("Huck Adventures", "huckadventures"),
    ("iFLIP4", "iflip4"),
    ("iHeartMedia", "iheartmedia"),
    ("InfiniteQuant", "infinitequant"),
    ("Interco", "interco"),
    ("Jade Global", "jadeglobal"),
    ("KOSTAL Group", "kostalgroup"),
    ("LAXIR", "laxir"),
    ("Microchip Technology", "microchip"),
    ("Red Bull", "redbull"),
    ("RRS Group", "rrsgroup"),
    ("SightCall", "sightcall"),
    ("StepStone Group", "stepstonegroup"),
    ("Wabtec", "wabtec"),
    ("WTW", "wtw"),
]

WORKABLE_COMPANIES = [
    # display_name, workable_account_slug
    ("Hugging Face", "huggingface"),
]
