"""
Company registry for the ATS poller.

Each entry maps a company to the ATS platform it posts jobs on, plus
whatever identifier that platform's API needs to look it up. Verified by
hitting the platform's public JSON API directly (see PR/commit history) --
don't add an entry here without confirming the API actually returns data
for that slug/tenant.
"""

GREENHOUSE_COMPANIES = [
    # display_name, board_slug
    ("Coinbase", "coinbase"),
    ("Waymo", "waymo"),
    ("Block", "block"),
    ("Anthropic", "anthropic"),
    ("Cloudflare", "cloudflare"),
    ("Stripe", "stripe"),
    ("Dropbox", "dropbox"),
    ("Duolingo", "duolingo"),
    ("Figma", "figma"),
    ("Databricks", "databricks"),
    ("Robinhood", "robinhood"),
    ("Ripple", "ripple"),
    ("Airtable", "airtable"),
    ("Airbnb", "airbnb"),
    ("Pinterest", "pinterest"),
    ("Reddit", "reddit"),
    ("Discord", "discord"),
    ("Twitch", "twitch"),
    ("Roblox", "roblox"),
    ("Epic Games", "epicgames"),
    ("Riot Games", "riotgames"),
    ("Asana", "asana"),
    ("Datadog", "datadog"),
    ("MongoDB", "mongodb"),
    ("Elastic", "elastic"),
    ("GitLab", "gitlab"),
    ("JetBrains", "jetbrains"),
    ("Vercel", "vercel"),
    ("Netlify", "netlify"),
    ("Twilio", "twilio"),
    ("Okta", "okta"),
    ("Zscaler", "zscaler"),
    ("Scale AI", "scaleai"),
    ("xAI", "xai"),
    ("DeepMind", "deepmind"),
    ("Inflection AI", "inflectionai"),
    ("Stability AI", "stabilityai"),
    ("Together AI", "togetherai"),
    ("Graphcore", "graphcore"),
    ("Tenstorrent", "tenstorrent"),
    ("Ubiquiti", "ubiquiti"),
    ("Rubrik", "rubrik"),
    ("Pure Storage", "purestorage"),
    ("Canonical", "canonical"),
    ("Cockroach Labs", "cockroachlabs"),
    ("PlanetScale", "planetscale"),
    ("Fivetran", "fivetran"),
    ("LaunchDarkly", "launchdarkly"),
    ("PagerDuty", "pagerduty"),
    ("New Relic", "newrelic"),
    ("Grafana Labs", "grafanalabs"),
    ("Honeycomb", "honeycomb"),
    ("Samsara", "samsara"),
    ("Motional", "motional"),
    ("Nuro", "nuro"),
    ("SpaceX", "spacex"),
    ("Rocket Lab", "rocketlab"),
    ("Planet Labs", "planetlabs"),
    ("Astranis", "astranis"),
    ("Lucid Motors", "lucidmotors"),
    ("Figure AI", "figureai"),
    ("Agility Robotics", "agilityrobotics"),
    ("Chime", "chime"),
    ("Affirm", "affirm"),
    ("Brex", "brex"),
    ("Mercury", "mercury"),
    ("Betterment", "betterment"),
    ("SoFi", "sofi"),
    ("Marqeta", "marqeta"),
    ("Adyen", "adyen"),
    ("Wise", "wise"),
    ("Jane Street", "janestreet"),
    ("Jump Trading", "jumptrading"),
    ("Akuna Capital", "akunacapital"),
    ("Optiver", "optiver"),
    ("Point72", "point72"),
    ("Instacart", "instacart"),
    ("Lyft", "lyft"),
    ("Squarespace", "squarespace"),
    ("Klaviyo", "klaviyo"),
    ("Intercom", "intercom"),
    ("Gusto", "gusto"),
    ("Remote", "remote"),
    ("Checkr", "checkr"),
    ("Carta", "carta"),
    ("LG Electronics", "lgelectronics"),
    ("Western Union", "westernunion"),
    ("McAfee", "mcafee"),
    ("Fastly", "fastly"),
    ("Peloton", "peloton"),
    ("Oura", "oura"),
    ("Coursera", "coursera"),
    ("Udemy", "udemy"),
    ("Udacity", "udacity"),
    ("Khan Academy", "khanacademy"),
    ("2U", "2u"),
    ("IXL Learning", "ixllearning"),
    ("ZipRecruiter", "ziprecruiter"),
    ("LinkedIn", "linkedin"),
    ("Upwork", "upwork"),
    ("Turing", "turing"),
    ("Instawork", "instawork"),
    ("Flex", "flex"),
    ("Venture Global", "ventureglobal"),
    ("Verkada", "verkada"),
]

LEVER_COMPANIES = [
    # display_name, company_slug
    ("Palantir", "palantir"),
    ("Neon", "neon"),
    ("Zoox", "zoox"),
    ("Shield AI", "shieldai"),
    ("Wealthfront", "wealthfront"),
    ("AngelList", "angellist"),
    ("Extreme Networks", "extremenetworks"),
]

ASHBY_COMPANIES = [
    # display_name, job_board_slug
    ("OpenAI", "openai"),
    ("Perplexity", "perplexity"),
    ("Cohere", "cohere"),
    ("Cerebras", "cerebras"),
    ("Harvey", "harvey"),
    ("Replit", "replit"),
    ("Runway", "runway"),
    ("ElevenLabs", "elevenlabs"),
    ("Supabase", "supabase"),
    ("Notion", "notion"),
    ("Ramp", "ramp"),
    ("Linear", "linear"),
    ("Vercel", "vercel"),
    ("Snowflake", "snowflake"),
    ("Pika", "pika"),
    ("Baseten", "baseten"),
    ("Deepgram", "deepgram"),
    ("Sierra", "sierra"),
    ("Writer", "writer"),
    ("Pinecone", "pinecone"),
    ("Weaviate", "weaviate"),
    ("Temporal", "temporal"),
    ("Warp", "warp"),
    ("Raycast", "raycast"),
    ("Browserbase", "browserbase"),
    ("Render", "render"),
    ("Railway", "railway"),
    ("Clerk", "clerk"),
    ("WorkOS", "workos"),
    ("Resend", "resend"),
    ("Wiz", "wiz"),
    ("Snyk", "snyk"),
    ("Cursor", "cursor"),
    ("Magic Patterns", "magicpatterns"),
    ("LangChain", "langchain"),
    ("Crusoe", "crusoe"),
    ("Lambda", "lambda"),
    ("Midjourney", "midjourney"),
    ("Physical Intelligence", "physicalintelligence"),
    ("Deel", "deel"),
    ("Convex", "convex-dev"),
    ("AfterQuery", "afterquery"),
    ("Agave", "agave"),
    ("Airbyte", "airbyte"),
    ("Anyscale", "anyscale"),
    ("Ashby", "ashby"),
    ("Auctor", "auctor"),
    ("Bland AI", "bland"),
    ("Circleback", "circleback"),
    ("Letta", "letta"),
    ("Modal", "modal"),
    ("Retell AI", "retell-ai"),
    ("Speak", "speak"),
    ("Uncountable", "uncountable"),
    ("Vapi", "vapi"),
    ("Giga", "gigaml"),
]

WORKDAY_COMPANIES = [
    # display_name, tenant, wd_host (e.g. "wd5"), site
    ("Adobe", "adobe", "wd5", "external_experienced"),
    ("Nvidia", "nvidia", "wd5", "NVIDIAExternalCareerSite"),
    ("Intel", "intel", "wd1", "External"),
    ("Analog Devices", "analogdevices", "wd1", "External"),
    ("Micron", "micron", "wd1", "External"),
    ("GlobalFoundries", "globalfoundries", "wd1", "External"),
    ("Cadence", "cadence", "wd1", "External_Careers"),
    ("Chewy", "chewy", "wd5", "External"),
    ("Vanguard", "vanguard", "wd5", "vanguard_External"),
    ("State Street", "statestreet", "wd1", "Global"),
    ("Boeing", "boeing", "wd1", "External_Careers"),
    ("Leidos", "leidos", "wd5", "External"),
    ("CACI", "caci", "wd1", "External"),
    ("Qualys", "qualys", "wd5", "Careers"),
    ("Trend Micro", "trendmicro", "wd3", "External"),
    ("Ciena", "ciena", "wd5", "Careers"),
    ("Pluralsight", "pluralsight", "wd1", "Careers"),
    ("3M", "3m", "wd1", "Search"),
    ("AES", "aes", "wd1", "AES_US"),
    ("Amgen", "amgen", "wd1", "Careers"),
    ("Applied Materials", "amat", "wd1", "External"),
    ("Arrow Electronics", "arrow", "wd1", "AC"),
    ("Bank of America", "ghr", "wd1", "Lateral-US"),
    ("Becton Dickinson", "bdx", "wd1", "EXTERNAL_CAREER_SITE_USA"),
    ("Biogen", "biibhr", "wd3", "external"),
    ("Bristol-Myers Squibb", "bristolmyerssquibb", "wd5", "BMS"),
    ("CDW", "cdw", "wd5", "Careers"),
    ("Chevron", "chevron", "wd5", "jobs"),
    ("Cigna", "cigna", "wd5", "cignacareers"),
    ("Conagra Brands", "conagrabrands", "wd1", "Careers_US"),
    ("ConocoPhillips", "conocophillips", "wd1", "eQuest"),
    ("Duke Energy", "dukeenergy", "wd1", "Search"),
    ("Expedia", "expedia", "wd108", "search"),
    ("Fidelity", "fmr", "wd1", "FidelityCareers"),
    ("Fiserv", "fiserv", "wd5", "EXT"),
    ("General Motors", "generalmotors", "wd5", "Careers_GM"),
    ("Gilead Sciences", "gilead", "wd1", "gileadcareers"),
    ("KLA", "kla", "wd1", "Search"),
    ("Mastercard", "mastercard", "wd1", "CorporateCareers"),
    ("Merck", "msd", "wd5", "SearchJobs"),
    ("Motorola Solutions", "motorolasolutions", "wd5", "Careers"),
    ("Pfizer", "pfizer", "wd1", "PfizerCareers"),
    ("Prudential Financial", "pru", "wd5", "Careers"),
    ("RTX", "globalhr", "wd5", "REC_RTX_Ext_Gateway"),
    ("Travelers", "travelers", "wd5", "External"),
    ("Truist Financial", "truist", "wd1", "Careers"),
]

# Not added, verified wrong or unresolvable when the user pasted a claimed
# Workday company list on 2026-08-19 (see git history for the fork's full
# verification report):
# - Wrong platform entirely (no adapter for these here): AMD (iCIMS),
#   Boston Scientific (Eightfold), Emerson Electric (Oracle Fusion), Ford
#   (Oracle Fusion), Honeywell (Oracle Fusion), Lam Research (Eightfold),
#   Texas Instruments (Oracle Fusion), United Airlines (Taleo -- the
#   uaa.wd12 Workday tenant found is only their flight-school subsidiary).
# - Not actually this company's board: Aflac (hit was Children's Healthcare
#   of Atlanta's "Aflac Cancer Center"), Cintas (hit was Northrop Grumman's
#   vendor board mentioning Cintas).
# - Stale: Discover Financial (being retired into Capital One's board
#   post-acquisition).
# - No working tenant/site found within a reasonable search budget:
#   Accenture, Abbott Laboratories (already covered separately via
#   custom_sites/adapters/abbott_careers.py on jobs.abbott, a different
#   site), Amphenol, Aramark, Archer Daniels Midland, Baker Hughes, Baxter
#   International, BlackRock, Blackstone, Bunge, C.H. Robinson Worldwide,
#   Capital One, CBRE, Citi, Comcast, Ecolab, Eli Lilly, Intuit, Jabil,
#   Johnson & Johnson, Northrop Grumman, Palo Alto Networks, Procter &
#   Gamble, Stryker, T-Mobile US, Thermo Fisher Scientific, UnitedHealth,
#   Verizon, Wells Fargo -- revisit if worth the WebSearch time later.

SMARTRECRUITERS_COMPANIES = [
    # display_name, company_identifier (as used in the API path)
    ("AbbVie", "abbvie"),
    ("Avery Dennison", "averydennison"),
    ("Builders FirstSource", "buildersfirstsource"),
    ("Celanese", "celanese"),
    ("Cencora", "cencora"),
    ("Freeport-McMoRan", "freeport-mcmoran"),
    ("Glean", "glean"),
    ("Henry Schein", "henryschein"),
    ("Kenvue", "kenvue"),
    ("Kimberly-Clark", "kimberlyclark"),
    ("Land O'Lakes", "landolakes"),
    ("Live Nation Entertainment", "livenationentertainment"),
    ("MGM Resorts International", "mgmresortsinternational"),
    ("Markel", "markel"),
    ("News Corp.", "newscorp"),
    ("Northwestern Mutual", "northwesternmutual"),
    ("ServiceNow", "servicenow"),
    ("Sonic Automotive", "sonicautomotive"),
    ("Western Digital", "westerndigital"),
]
