"""
Company registry for the ATS poller.

Each entry maps a company to the ATS platform it posts jobs on, plus
whatever identifier that platform's API needs to look it up. Verified by
hitting the platform's public JSON API directly (see PR/commit history) --
don't add an entry here without confirming the API actually returns data
for that slug/tenant.
"""

GREENHOUSE_COMPANIES = [
    # display_name, board_slug
    ("Coinbase", "coinbase"),
    ("Waymo", "waymo"),
    ("Block", "block"),
    ("Anthropic", "anthropic"),
    ("Cloudflare", "cloudflare"),
    ("Stripe", "stripe"),
    ("Dropbox", "dropbox"),
    ("Duolingo", "duolingo"),
    ("Figma", "figma"),
    ("Databricks", "databricks"),
    ("Robinhood", "robinhood"),
    ("Ripple", "ripple"),
    ("Airtable", "airtable"),
    ("Airbnb", "airbnb"),
    ("Pinterest", "pinterest"),
    ("Reddit", "reddit"),
    ("Discord", "discord"),
    ("Twitch", "twitch"),
    ("Roblox", "roblox"),
    ("Epic Games", "epicgames"),
    ("Riot Games", "riotgames"),
    ("Asana", "asana"),
    ("Datadog", "datadog"),
    ("MongoDB", "mongodb"),
    ("Elastic", "elastic"),
    ("GitLab", "gitlab"),
    ("JetBrains", "jetbrains"),
    ("Vercel", "vercel"),
    ("Netlify", "netlify"),
    ("Twilio", "twilio"),
    ("Okta", "okta"),
    ("Zscaler", "zscaler"),
    ("Scale AI", "scaleai"),
    ("xAI", "xai"),
    ("DeepMind", "deepmind"),
    ("Inflection AI", "inflectionai"),
    ("Stability AI", "stabilityai"),
    ("Together AI", "togetherai"),
    ("Graphcore", "graphcore"),
    ("Tenstorrent", "tenstorrent"),
    ("Ubiquiti", "ubiquiti"),
    ("Rubrik", "rubrik"),
    ("Pure Storage", "purestorage"),
    ("Canonical", "canonical"),
    ("Cockroach Labs", "cockroachlabs"),
    ("PlanetScale", "planetscale"),
    ("Fivetran", "fivetran"),
    ("LaunchDarkly", "launchdarkly"),
    ("PagerDuty", "pagerduty"),
    ("New Relic", "newrelic"),
    ("Grafana Labs", "grafanalabs"),
    ("Honeycomb", "honeycomb"),
    ("Samsara", "samsara"),
    ("Motional", "motional"),
    ("Nuro", "nuro"),
    ("SpaceX", "spacex"),
    ("Rocket Lab", "rocketlab"),
    ("Planet Labs", "planetlabs"),
    ("Astranis", "astranis"),
    ("Lucid Motors", "lucidmotors"),
    ("Figure AI", "figureai"),
    ("Agility Robotics", "agilityrobotics"),
    ("Chime", "chime"),
    ("Affirm", "affirm"),
    ("Brex", "brex"),
    ("Mercury", "mercury"),
    ("Betterment", "betterment"),
    ("SoFi", "sofi"),
    ("Marqeta", "marqeta"),
    ("Adyen", "adyen"),
    ("Wise", "wise"),
    ("Jane Street", "janestreet"),
    ("Jump Trading", "jumptrading"),
    ("Akuna Capital", "akunacapital"),
    ("Optiver", "optiver"),
    ("Point72", "point72"),
    ("Instacart", "instacart"),
    ("Lyft", "lyft"),
    ("Squarespace", "squarespace"),
    ("Klaviyo", "klaviyo"),
    ("Intercom", "intercom"),
    ("Gusto", "gusto"),
    ("Remote", "remote"),
    ("Checkr", "checkr"),
    ("Carta", "carta"),
    ("LG Electronics", "lgelectronics"),
    ("Western Union", "westernunion"),
    ("McAfee", "mcafee"),
    ("Fastly", "fastly"),
    ("Peloton", "peloton"),
    ("Oura", "oura"),
    ("Coursera", "coursera"),
    ("Udemy", "udemy"),
    ("Udacity", "udacity"),
    ("Khan Academy", "khanacademy"),
    ("2U", "2u"),
    ("IXL Learning", "ixllearning"),
    ("ZipRecruiter", "ziprecruiter"),
    ("LinkedIn", "linkedin"),
    ("Upwork", "upwork"),
    ("Turing", "turing"),
    ("Instawork", "instawork"),
]

LEVER_COMPANIES = [
    # display_name, company_slug
    ("Palantir", "palantir"),
    ("Neon", "neon"),
    ("Zoox", "zoox"),
    ("Shield AI", "shieldai"),
    ("Wealthfront", "wealthfront"),
    ("AngelList", "angellist"),
    ("Extreme Networks", "extremenetworks"),
]

ASHBY_COMPANIES = [
    # display_name, job_board_slug
    ("OpenAI", "openai"),
    ("Perplexity", "perplexity"),
    ("Cohere", "cohere"),
    ("Cerebras", "cerebras"),
    ("Harvey", "harvey"),
    ("Replit", "replit"),
    ("Runway", "runway"),
    ("ElevenLabs", "elevenlabs"),
    ("Supabase", "supabase"),
    ("Notion", "notion"),
    ("Ramp", "ramp"),
    ("Linear", "linear"),
    ("Vercel", "vercel"),
    ("Snowflake", "snowflake"),
    ("Pika", "pika"),
    ("Baseten", "baseten"),
    ("Deepgram", "deepgram"),
    ("Sierra", "sierra"),
    ("Writer", "writer"),
    ("Pinecone", "pinecone"),
    ("Weaviate", "weaviate"),
    ("Temporal", "temporal"),
    ("Warp", "warp"),
    ("Raycast", "raycast"),
    ("Browserbase", "browserbase"),
    ("Render", "render"),
    ("Railway", "railway"),
    ("Clerk", "clerk"),
    ("WorkOS", "workos"),
    ("Resend", "resend"),
    ("Wiz", "wiz"),
    ("Snyk", "snyk"),
    ("Cursor", "cursor"),
    ("Magic Patterns", "magicpatterns"),
    ("LangChain", "langchain"),
    ("Crusoe", "crusoe"),
    ("Lambda", "lambda"),
    ("Midjourney", "midjourney"),
    ("Physical Intelligence", "physicalintelligence"),
    ("Deel", "deel"),
    ("Convex", "convex-dev"),
]

WORKDAY_COMPANIES = [
    # display_name, tenant, wd_host (e.g. "wd5"), site
    ("Adobe", "adobe", "wd5", "external_experienced"),
    ("Nvidia", "nvidia", "wd5", "NVIDIAExternalCareerSite"),
    ("Intel", "intel", "wd1", "External"),
    ("Analog Devices", "analogdevices", "wd1", "External"),
    ("Micron", "micron", "wd1", "External"),
    ("GlobalFoundries", "globalfoundries", "wd1", "External"),
    ("Cadence", "cadence", "wd1", "External_Careers"),
    ("Chewy", "chewy", "wd5", "External"),
    ("Vanguard", "vanguard", "wd5", "vanguard_External"),
    ("State Street", "statestreet", "wd1", "Global"),
    ("Boeing", "boeing", "wd1", "External_Careers"),
    ("Leidos", "leidos", "wd5", "External"),
    ("CACI", "caci", "wd1", "External"),
    ("Qualys", "qualys", "wd5", "Careers"),
    ("Trend Micro", "trendmicro", "wd3", "External"),
    ("Ciena", "ciena", "wd5", "Careers"),
    ("Pluralsight", "pluralsight", "wd1", "Careers"),
]
